version: '3'
services:
  strapi-backend:
    image: strapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      INSTANCE_CONNECTION_NAME: ${INSTANCE_CONNECTION_NAME:-travelsupportdbrestore.mysql.database.azure.com}
      DATABASE_NAME: ${DATABASE_NAME:-intranetdb}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-traveladmin@travelsupportdbrestore}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-tr@velsupport1234}
      DATABASE_SSL: ${DATABASE_SSL:-false}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}:-hejhej
      CLOUDINARY_NAME: ${CLOUDINARY_NAME:-dqy1t1n9o}
      CLOUDINARY_KEY: ${CLOUDINARY_KEY:-325872555751884}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET:-s9Xs8_Ljx--_mhWc6lpdbek_Cxc}
      # HOST: ${HOST:-localhost}
      # PORT: ${PORT:-1337}
    ports:
      - 80:1337
      # - '${PORT:-80}:${PORT:-1337}'
