# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - travelsupportprod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://travelsupportcc.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f01a5cc5e9ac49709c6430fa9b5034e0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c3a4c600e56e4ede901c051740e72f4f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: travelsupportcc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f01a5cc5e9ac49709c6430fa9b5034e0 }}/strapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'travelsupportprod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_96dfb64682cc474cbf481e589c152494 }}
        images: 'travelsupportcc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f01a5cc5e9ac49709c6430fa9b5034e0 }}/strapi:${{ github.sha }}'