# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - travelstrapitest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://travelsupportcc.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b6b624141c494f43a0a43f36442151de }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bdf2b361a0a143018892d8567b61fee5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: travelsupportcc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b6b624141c494f43a0a43f36442151de }}/strapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'travelsupportstrapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_04a99e655294499cadded5c85cdd375f }}
        images: 'travelsupportcc.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b6b624141c494f43a0a43f36442151de }}/strapi:${{ github.sha }}'
